---
title: "Lab 5 Final Exam Review"
author: "Owen Cheung, Steven Tran"
date: '2022-08-17'
output:
  word_document: default
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set
library(tidyverse)
```

# Question 1
```{r}
point_est = (23.12 - 17.90)
# 5.22
SE = sqrt((5.01^2 / 27) + (2.28^2 / 21))
# 1.084978
# a)
# df = 20, so using t table for 99%, the statistic should be 2.528
upper <- point_est + (2.528 * SE)
lower <- point_est - (2.528 * SE)
# (2.477177, 7.962823)
# we are 99% confident that the average 

# b)
a = 0.01
# H0: difference in means is 0, Ha: difference in means is not 0
t = point_est - 0 / SE
# t statistic = 4.81116
df = min((27-1), (21-1))
# df = 20
pval <- pt(q = 4.81116, df = 20)
# p val = 0.9999469
# p value is large so we do not reject H0 the data does not provide convincing evidence that suggests the difference in mean sick days between blue collar workers and white collars workers is not 0
```

# Question 2
```{r}
n <- 12
#confidence interval of 95% for mean is (46.2, 56.9)

# a) what is the margin of error for this confidence interval
ME <- (56.9 - 46.2) / 2
ME
# margin of error = 5.35

# b) what is the point estimate for that sample
# finding sample mean
samp_mean <- 56.9 - ME
samp_mean
# sample mean = 51.55

# c) find the standard deviation for that sample
# 95% = 2 SDs away from mean
SD <- (56.9 - 46.2) / 4
SD
# standard deviation = 2.675

```

# Question 3
```{r}

### 3A) Test the hypothesis H0: μ = 65 against H1: μ > 65. Find the test statistic and report your conclusion.

$ H0: μ = 65 $ 

$ Ha: μ > 65 $

df <- c(60, 62, 63, 63, 63, 66, 66, 66, 66, 67, 67, 68, 68, 68, 69, 70, 71, 71)

mean(df)


sd(df)


t <- (66-65) / ((3.12485) / sqrt(18))

pt(1.357, 17, lower.tail = FALSE)


Since p-val = 0.096 > alpha = 0.05, we fail to reject the null hypothesis that the mean height of all women is equal to 65. We do not have convincing evidence for the alternative hypothesis that the mean height of all women is greater than 65. 


### B) Test the hypothesis H0: p = 0.5 against H1: p > 0.5. Find the test statistic and report your conclusion. 


$ H0: p = 0.5 $

$H1: p > 0.5$

Z = (((13/18) - 0.5) / sqrt(0.5^2/18))



1- p(Z > 1.89) = 0.0294

Since Pval = 0.0294 < alpha = 0.05, we reject the null hypothesis. We have convincing evidence that the proportion of women taller than 65 inches is greater than 0.5.


```

# Question 4
```{r}


### 4A) 


$ H0: p(dem) = p(rep) $

$ H0: p(dem) =/ = p(rep) $

phat <- (127 + 131)/ 1007

q <- 1 - phat


Z <- (0.2 - 0.35) / sqrt((phat*q)((1/635)+(1/372)))

Zstat <- 5.26


Since p-val = 1 > 0.05, we fail to reject the null hypothesis. We do not have convincing evidence that there is a difference in the proportion of Democrats and Republicans who said that driving while impaired by marijuana poses a very serious threat. 


### B)


i) It would not change. The sample statistic is the proportion of democrats subtracted by the proportion of republicans, or vice versa.  

ii) It would be different, because in hypothesis testing, you are pooling both proportions to create the phat and in confidence interval you re adding both confidence interval.

iii) (0.09, 0.21)

We are 95% confident that the difference in democrats and republicans on their opionin that marijuana poses a very serious threat to be between 0.09 and 0.21. 


Lower <- 0.15 - (1.96)*(0.029)
Upper <- 0.15 + (1.96)*(0.029)

standard_error <- sqrt(((0.2*0.8) / 635) + ((0.35*0.65) / 372))


```

# Question 5
```{r}
handout1 <- read.csv("data/Handout 1.csv", stringsAsFactors = FALSE)
head(handout1)
grouped <- handout1 %>%
  group_by(SEX) %>%
  summarise_at(vars(SALARY), list(mean_salary = mean))
grouped



grouped_sd <- handout1 %>%
  group_by(SEX) %>%
  summarise_at(vars(SALARY), list(sd_salary = sd))
grouped_sd
# seems like a difference in means question
# hypothesis
# H0: no difference, Ha: difference

Hypothesis: 
  
Ho: μ1 = μ2


Ho: μ1 =/= μ2


Where μ1 is the population mean for the males and μ2 is the population mean for the females. 



s <- ((80*7.868) + (68*10.17)) / (148)
seed <- sqrt((s/81)+ (s/69))

lower <- (0.044 - 1.96*seed)
upper <- (0.044 + 1.96*seed)


We are 95% confident that the mean difference in commitment scores with respect to sex lies between -0.92 and 1.0. Since 0 lies between these intervals, we do not have convincing evidence that there is a difference in commitment scores with respect to sex. 

```

